default:
	python array123.py
	python array_count9.py
	python big_diff.py
	python count_evens.py
	python front_times.py
	python has22.py
	python string_match.py
	python string_splosion.py
	python string_times.py
	python sum67.py
	python random_table.py